# 端口号
server:
  port: 9090
# 数据源
spring:
  datasource:
    druid:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://localhost:3306/springboot_biye?serverTimezone=GMT%2B8&useSSL=false&characterEncoding=utf-8
      username: root
      password: 123456
  # 解决前端与数据库日期格式不一致问题
  jackson:
    dateFormat: yyyy-MM-dd HH:mm:ss
    timeZone: GMT+8
  servlet:
    multipart:
      # 设置单个文件大小
      max-file-size: 50MB
      # 设置单次请求文件的总大小
      max-request-size: 50MB
  mail:
    # QQ邮箱
    host: smtp.qq.com
    # 院级/校级
    username: "2749775885@qq.com"
    password: "pznpwmwscpaqdfbg"
    port: 587


mybatis:
  # 指定mapper隐射文件
  mapper-locations: classpath:mappers/*.xml
  # 配置别名, 在Mapper.xml中只需使用类名即可
  type-aliases-package: com.zgy.springboot_byte.domain
  # 配置mybatis运行日志
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

